# Getting started with TensorFlow: A guide to the fundamentals

###  Creating Tensors with `tf.constant()`

In [ ]:
import tensorflow as tf

In [ ]:
# Create a scalar (rank 0 tensor)
scalar = tf.constant(7)
scalar, scalar.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=7>, 0)

In [ ]:
# Create a vector (more than 0 dimensions)
vector = tf.constant([10, 10])
vector, vector.ndim

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>, 1)

In [ ]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix, matrix.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10]], dtype=int32)>,
 2)

In [ ]:
# By default, TensorFlow creates tensors with either an int32 or float32 datatype.
# Create another matrix and define the datatype
matrix2 = tf.constant([[5., 3.],
                       [2., 8.]], dtype=tf.float16)
matrix2, matrix2.ndim

(<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
 array([[5., 3.],
        [2., 8.]], dtype=float16)>,
 2)

In [ ]:
# How about a tensor? (more than 2 dimensions, although, all of the above items are also technically tensors)
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

### Creating Tensors with `tf.Variable()`

The difference between `tf.Variable()` and `tf.constant()` is tensors created with `tf.constant()` are **immutable** (can't be changed, can only be used to create a new tensor), where as, tensors created with `tf.Variable()` are **mutable** (can be changed).

In [ ]:
# Create the same tensor with tf.Variable() and tf.constant()
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# To change an element of a tf.Variable() tensor requires the assign() method.
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating random tensors

In [ ]:
# create tensor from a normal distribution
tf.random.set_seed(42)
random_1 = tf.random.normal(shape=(3,3))
random_1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.3274685, -0.8426258,  0.3194337],
       [-1.4075519, -2.3880599, -1.0392479],
       [-0.5573232,  0.539707 ,  1.6994323]], dtype=float32)>

---
[tf.random.set_seed()](https://www.tensorflow.org/api_docs/python/tf/random/set_seed) documentation:

> *4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.*

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data)
tf.random.shuffle(random_1, seed=24)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.5573232,  0.539707 ,  1.6994323],
       [ 0.3274685, -0.8426258,  0.3194337],
       [-1.4075519, -2.3880599, -1.0392479]], dtype=float32)>

### Other ways to make tensors

In [ ]:
# Make a tensor of all ones
tf.ones(shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
# Make a tensor of all zeros
tf.zeros(shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)  # 24 elements
A = tf.constant(numpy_A, shape=(2, 3, 4))

numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

# Getting information from tensors (shape, rank, size)
---
> * **Shape**: The length (number of elements) of each of the dimensions of a tensor.
* **Rank**: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
* **Axis or Dimension**: A particular dimension of a tensor.
* **Size**: The total number of items in the tensor.

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor), "numpy:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): tf.Tensor(120, shape=(), dtype=int32) numpy: 120


In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
rank_2_tensor[1, :]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

### You can also add dimensions to your tensor whilst keeping the same information:
---
> * [tf.newaxis](https://www.tensorflow.org/api_docs/python/tf/Tensor)
* [tf.expand_dims()](https://www.tensorflow.org/api_docs/python/tf/expand_dims)

In [ ]:
# Add an extra dimension (to the end) - tf.newaxis
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
rank_2_tensor[:, tf.newaxis, :]

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [ ]:
# Add an extra dimension (to the end) - tf.expand_dims()
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

# Manipulating tensors (tensor operations)

In [ ]:
# Create (3, 2) tensor
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

---
> * [tf.reshape()](https://www.tensorflow.org/api_docs/python/tf/reshape) - allows us to reshape a tensor into a defined shape.
* [tf.transpose()](https://www.tensorflow.org/api_docs/python/tf/transpose) - switches the dimensions of a given tensor.

In [ ]:
# Example of reshape (3, 2) -> (2, 3)
Y1 = tf.reshape(Y, shape=(2, 3))
Y1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
# Example of transpose (3, 2) -> (2, 3)
Y2 = tf.transpose(Y)
Y2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [ 8, 10, 12]], dtype=int32)>

In [ ]:
tf.matmul(X, Y1), X @ Y1

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]], dtype=int32)>)

In [ ]:
tf.matmul(X, Y2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

### Changing the datatype of a tensor
---

In [ ]:
B = tf.constant([1.7, 7.4])
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>

In [ ]:
B2 = tf.cast(B, dtype=tf.int32)
B2

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7], dtype=int32)>

### Getting the absolute value
---

In [ ]:
C = tf.constant([-7, -5])
tf.abs(C)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 5], dtype=int32)>

### Finding the min, max, mean, sum (aggregation)

---
To do so, aggregation methods typically have the syntax `reduce()_[action]`, such as:

* [tf.reduce_min()](https://www.tensorflow.org/api_docs/python/tf/math/reduce_min) - find the minimum value in a tensor.
* [tf.reduce_max()](https://www.tensorflow.org/api_docs/python/tf/math/reduce_max) - find the maximum value in a tensor (helpful for when you want to find the highest prediction probability).
* **tf.reduce_mean()** - find the mean of all elements in a tensor.
* **tf.reduce_sum()** - find the sum of all elements in a tensor.

You can also find: **tf.reduce_prod()**, **tf.reduce_std()**, **tf.reduce_variance()**

*Note: typically, each of these is under the math module, e.g. tf.math.reduce_min() but you can use the alias tf.reduce_min().*

In [ ]:
D = tf.constant(np.random.randint(low=1, high=30, size=10))
D

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 9, 14,  6, 27, 17, 24, 24,  4, 25, 14])>

In [ ]:
tf.reduce_min(D), tf.reduce_max(D), tf.reduce_mean(D), tf.reduce_sum(D), tf.reduce_prod(D)

(<tf.Tensor: shape=(), dtype=int64, numpy=4>,
 <tf.Tensor: shape=(), dtype=int64, numpy=27>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=int64, numpy=164>,
 <tf.Tensor: shape=(), dtype=int64, numpy=279824025600>)

### Finding the positional maximum and minimum
---
* **tf.argmax()** - find the position of the maximum element in a given tensor.
* **tf.argmin()** - find the position of the minimum element in a given tensor.

In [ ]:
E = tf.constant([2, 20, 30, 2, 3, 6, 30])
E

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([ 2, 20, 30,  2,  3,  6, 30], dtype=int32)>

In [ ]:
tf.argmin(E).numpy(), tf.argmax(E).numpy()

(np.int64(0), np.int64(2))

### Squeezing a tensor (removing all single dimensions)
---

In [ ]:
# Create a rank 5 (5 dimensions) tensor of 50 numbers between 0 and 100
F = tf.constant(np.random.randint(0, 100, 50), shape=(1, 1, 1, 1, 50))
F.shape, F.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [ ]:
F_squeezed = tf.squeeze(F)
F_squeezed.shape, F_squeezed.ndim

(TensorShape([50]), 1)

### One-hot encoding
---




In [ ]:
# If you have a tensor of indicies and would like to
# one-hot encode it, you can use tf.one_hot().
some_list = [0, 1, 2, 3]

tf.one_hot(some_list, depth=5)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list, depth=5, on_value="Yes", off_value="No")

<tf.Tensor: shape=(4, 5), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'No', b'Yes', b'No']], dtype=object)>

### Squaring, log, square root
---

In [ ]:
G = tf.constant(np.arange(1, 10))
G

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [ ]:
G_squared = tf.square(G)
G_squared

<tf.Tensor: shape=(9,), dtype=int64, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [ ]:
# Find the squareroot (will error), needs to be non-integer

G = tf.sqrt(tf.cast(G_squared, dtype=tf.float32))
G

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>

In [ ]:
# Find the log (input also needs to be float)
tf.math.log(G)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Manipulating tf.Variable tensors
---

In [ ]:
H = tf.Variable([10, 7])
H[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
I = tf.Variable(np.arange(0,5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [ ]:
I.assign([10,1,2,3,50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10,  1,  2,  3, 50])>

In [ ]:
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([20, 11, 12, 13, 60])>

In [ ]:
I.assign_sub([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10,  1,  2,  3, 50])>

# Tensors and NumPy

* **np.array()** - pass a tensor to convert to an ndarray (NumPy's main datatype).
* **tensor.numpy()** - call on a tensor to convert to an ndarray.

**By default tensors have dtype=float32, where as NumPy arrays have dtype=float64**

In [ ]:
# Create a tensor from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert tensor J to NumPy with np.array()
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

# Using @tf.function

In the `@tf.function` decorator case, it turns a Python function into a callable TensorFlow graph. Which is a fancy way of saying, if you've written your own Python function, and you decorate it with `@tf.function`, when you export your code (to potentially run on another device), TensorFlow will attempt to convert it into a fast(er) version of itself (by making it part of a computation graph).

In [83]:
# Create a simple function
def function(x, y):
  return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))

function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [84]:
# Create the same function and decorate it with tf.function
@tf.function
def tf_function(x, y):
  return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>